name: Deploy to AlwaysData

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/your-user/your-project

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
